# Config file for all model training settings

debug: False
device: 'cuda'

model:
  name: 'deepspot'
  pretrained: ''
  input_channels: 1
  dropout_rate: 0.2
  conv_block4_filters: 128
  identity_block_filters: 128

training:
  batch_size: 128
  batch_size_val: 128
  epochs: 50
  loss: 'deepspot'
  optimizer: 'adam'
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: 'reducelronplateau'
  scheduler_params:
    step_size: 10
    gamma: 0.1
    patience: 5
    factor: 0.1

data:
  root_dir: '/opt/ml/input/data/train'
  data_dir: 'data_z1_y256_x256_big_mask'
  #root_dir: '/Users/joshuastiller/Code/spotDetector/data'
  #data_dir: 'output_z1'
  dataset: 'deepSpot'
  train_file: 'patches_train.hdf5'
  val_file: 'patches_val.hdf5'
  bit_depth: 8
  filter_name:
  mode: '2D'
  input_size: [256, 256]
  num_workers: 8
  pin_memory: True
  augmentations:
    'horizontal_flip' : True
    'vertical_flip': True
    'color_jitter' : True

checkpoint:
  dir: 'checkpoints'
  save_best_only: True
  monitor_metric: 'val_loss'
  mode: 'min'
